export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'


export const GET_ASSIGNMENT_LIST_START = 'GET_ASSIGNMENT_LIST_START'
export const GET_ASSIGNMENT_LIST_SUCCESS = 'GET_ASSIGNMENT_LIST_SUCCESS'
export const GET_ASSIGNMENT_LIST_FAIL = 'GET_ASSIGNMENT_LIST_FAIL'


export const GET_ASSIGNMENT_START = 'GET_ASSIGNMENT_START'
export const GET_ASSIGNMENT_SUCCESS = 'GET_ASSIGNMENT_SUCCESS'
export const GET_ASSIGNMENT_FAIL = 'GET_ASSIGNMENT_FAIL'
export const GET_ASSIGNMENT_TIMEDOUT = 'GET_ASSIGNMENT_TIMEDOUT'


export const GET_STUDENT_PERFORMANCE_START = 'GET_STUDENT_PERFORMANCE_START'
export const GET_STUDENT_PERFORMANCE_SUCCESS = 'GET_STUDENT_PERFORMANCE_SUCCESS'
export const GET_STUDENT_PERFORMANCE_FAILED = 'GET_STUDENT_PERFORMANCE_FAILED'

export const SUBMIT_ASSESSMENT_START = 'SUBMIT_ASSESSMENT_START'
export const SUBMIT_ASSESSMENT_SUCCESS = 'SUBMIT_ASSESSMENT_SUCCESS'
export const SUBMIT_ASSESSMENT_FAILED = 'SUBMIT_ASSESSMENT_FAILED'