# Generated by Django 3.2 on 2021-04-24 05:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment',
            new_name='Assesment',
        ),
        migrations.RenameModel(
            old_name='AssignmentPerformance',
            new_name='AssesmentPerformance',
        ),
    ]
