# Generated by Django 3.2 on 2021-05-03 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizApp', '0003_alter_question_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesmentperformance',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment', to='quizApp.assesment'),
        ),
        migrations.AlterField(
            model_name='assesmentperformance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
