# Generated by Django 3.2 on 2021-05-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0004_auto_20210503_1428'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assesment',
            unique_together={('subject', 'topic')},
        ),
    ]
