# Generated by Django 3.2 on 2021-05-03 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0005_alter_assesment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assesment',
            unique_together=set(),
        ),
    ]
